name: Build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js action
      uses: actions/setup-node@v1
      with:
        node-version: 10.14
    - name: Build it
      run: |
        cd app
        yarn install
        yarn run build
      env:
        CI: true
